name: cell
channels:
  - conda-forge
  - pytorch
dependencies:
  - black=22.10.0
  - colorlog=6.7.0
  - ipykernel=6.16.1
  - ipython=8.5.0
  - ipywidgets=8.0.2
  - kaggle=1.5.12
  - numpy=1.23.4
  - pandas=1.5.1
  - pip=22.3
  - pyarrow=9.0.0
  - pytables=3.7.0
  - python=3.10.6
  - pytorch=1.12.1
  - pytorch-lightning=1.7.7
  - scikit-learn=1.1.2
  - scipy=1.9.3
  - seaborn=0.12.1
  - setuptools=65.5.0
  - xarray=2022.10.0