[tool.black]
line-length = 120
target-version = ["py37"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
  | data
)/
'''